name: setup foundry and yarn
description: 'checkout setup yarn and foundry'

inputs:
  node-version:
    description: 'Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0.'
    default: "18.15"
  registry-url:
    description: 'Optional registry to set up for auth. Will set the registry in a project level .npmrc and .yarnrc file, and set up auth to read in from env.NODE_AUTH_TOKEN.'
    default: https://npm.pkg.github.com/
  scope:
    description: 'Optional scope for authenticating against scoped registries. Will fall back to the repository owner when using the GitHub Packages registry (https://npm.pkg.github.com/).'
  cache:
    description: 'Used to specify a package manager for caching in the default directory. Supported values: npm, yarn, pnpm.'
    default: yarn
  ignore-scripts:
    description: install with ignore-scripts
    default: "true"

outputs:
  cache-hit-foundry:
    description: 'A boolean value to indicate if a foundry cache was hit.'
    value: ${{ steps.cache-foundry.outputs.cache-hit }}
  cache-hit:
    description: 'A boolean value to indicate if a cache was hit.'
    value: ${{ steps.setup-node.outputs.cache-hit }}
  node-version:
    description: 'The installed node version.'
    value: ${{ steps.setup-node.outputs.node-version }}

runs:
  using: composite
  steps:
  - uses: actions/checkout@v3
    with:
      submodules: recursive
  - name: Cache foundry
    id: cache-foundry
    uses: actions/cache@v3
    with:
      path: ~/.foundry
      key: ${{ runner.os }}-foundry
  - uses: onbjerg/foundry-toolchain@v1
    with:
      version: nightly
  - uses: actions/setup-node@v3
    id: setup-node
    with:
      node-version: ${{ inputs.node-version }}
      cache: ${{ inputs.cache }}
      registry-url: ${{ inputs.registry-url }}
      scope: ${{ inputs.scope }}
  - run: ${{ inputs.cache }} install ${{ (inputs.ignore-scripts == 'true') && '--ignore-scripts' || '' }}
    shell: bash
